services:
  mongo:
    image: initialized-mongo
    container_name: mongo-container
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: the_username
      MONGO_INITDB_ROOT_PASSWORD: the_password
      MONGO_INITDB_DATABASE: the_database
    networks:
      - prod

  redis:
    image: redis:latest
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis_data:/data
    networks:
      - prod

  server:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    image: todo-backend
    container_name: todo-backend
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379 
    networks:
      - prod

  app:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    image: todo-frontend
    container_name: todo-frontend
    hostname: todo-frontend
    networks:
      - prod

  proxy:
    image: nginx:1.21-alpine
    container_name: reverse-proxy
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - server 
    networks:
      - prod

networks:
  prod:
