
services:
  mongo:
    image: initialized-mongo
    container_name: mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: the_username
      MONGO_INITDB_ROOT_PASSWORD: the_password
      MONGO_INITDB_DATABASE: the_database
    networks:
      - dev

  redis:
    image: redis:latest
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis_data:/data
    networks:
      - dev

  server:
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    container_name: todo-backend-dev
    volumes:
      - ./todo-backend:/usr/src/app
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379 
    depends_on:
      - mongo
    networks:
      - dev

  app:
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    container_name: todo-frontend-dev
    volumes:
      - ./todo-frontend:/usr/src/app
    networks:
      - dev

  proxy:
    image: nginx:1.21-alpine
    container_name: reverse-proxy
    ports:
      - 8080:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - server 
    networks:
      - dev

networks:
  dev:
