services:
  mongo:
    image: initialized-mongo
    container_name: mongo-container
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: the_username
      MONGO_INITDB_ROOT_PASSWORD: the_password
      MONGO_INITDB_DATABASE: the_database
    networks:
      - backend

  server:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: todo-backend-dev
    container_name: todo-backend-dev
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://localhost:6379 
    networks:
      - backend
    volumes:
      - ./:/usr/src/app

networks:
  backend:
