services:
  app:
    build:
      context: ./notes-backend
      dockerfile: Dockerfile
    image: notes
    container_name: notes
    environment:
      - MONGO_URL=mongodb+srv://eki:kannaa@mangodb.ml2nd.mongodb.net/Notes?retryWrites=true&w=majority&appName=MangoDB
    networks:
      - prod

  proxy:
    image: nginx:1.21-alpine
    container_name: reverse-proxy
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app 
    networks:
      - prod

networks:
  prod:
